matrix:
  include:
    - language: python
      python:
        - "3.5"
        - "3.6"
      addons:
        apt:
          packages:
      before_script:
        - cd py
      install:
        - pip3 install -e .[dev]
        - pip3 install coveralls
      script:
        - python3 precommit.py
        - coveralls
    - language: cpp
      os: linux
      dist: xenial
      compiler:
        - clang
        - gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - g++-6
            - clang-3.8
      install:
        - make get-deps
        - "[ $CXX = g++ ] && export CXX=g++-6 || true"
        - "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
      before_script:
        - cd cpp
      script:
        - make
        - make test